apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment
  namespace: default # or your preferred namespace
spec:
  replicas: 2 # Number of pods to run
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: digerate/my-node-app:latest # Use your actual image
        ports:
        - containerPort: 80
