apiVersion: apps/v1
kind: Deployment
metadata:
  name: enhanced-node-app-deployment  
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: enhanced-node-app  
  template:
    metadata:
      labels:
        app: enhanced-node-app  
    spec:
      containers:
      - name: enhanced-node-app  # 
        image: digerate/enhanced-node-app:latest  
        ports:
        - containerPort: 3000
        env:
        - name: COSMOS_DB_URI
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: COSMOS_DB_URI
        - name: COSMOS_DB_PRIMARY_KEY
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: COSMOS_DB_PRIMARY_KEY
        - name: COSMOS_DB_DATABASE_ID
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: COSMOS_DB_DATABASE_ID
        - name: COSMOS_DB_CONTAINER_ID
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: COSMOS_DB_CONTAINER_ID
        - name: USE_COSMOS_DB
          value: "true"