apiVersion: apps/v1
kind: Deployment
metadata:
  name: enhanced-node-app-deployment  
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: enhanced-node-app  
  template:
    metadata:
      labels:
        app: enhanced-node-app  
    spec:
      containers:
      - name: enhanced-node-app  # 
        image: digerate/enhanced-node-app:latest  
        ports:
        - containerPort: 3000  


