apiVersion: apps/v1
kind: Deployment
metadata:
  name: enhanced-node-app-deployment  
  namespace: default
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: enhanced-node-app  # Update the label to match the new app name
  template:
    metadata:
      labels:
        app: enhanced-node-app  # Update the label to match the new app name
    spec:
      containers:
      - name: enhanced-node-app  # 
        image: digerate/enhanced-node-app:latest  # Update the image to point to the new Docker image
        ports:
        - containerPort: 80  # Make sure this port matches the port your app is configured to listen on
