name: Deploy AKS Cluster CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform  # Deploy AKS Cluster 
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.4
        terraform_wrapper: true

    - name: Terraform Init and Apply
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        LOCATION: ${{ secrets.LOCATION }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        terraform init
        terraform apply -auto-approve \
          -var="resource_group_name=${RESOURCE_GROUP_NAME}" \
          -var="cluster_name=${CLUSTER_NAME}" \
          -var="location=${LOCATION}" \
          -var="ssh_public_key=${SSH_PUBLIC_KEY}"

