name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker image
      run: |
        docker build -t digerate/my-node-app:${{ github.sha }} ./my-node-app
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push digerate/my-node-app:${{ github.sha }}
        env:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}  

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Deploy to AKS
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ./kubeconfig
        export KUBECONFIG=./kubeconfig
        kubectl set image deployment/my-node-app-deployment my-node-app=yourdockerhubusername/my-node-app:${{ github.sha }}
