name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker image
      run: |
          docker build -t digerate/enhanced-node-app:${{ github.sha }} ./enhanced-node-app
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker push digerate/enhanced-node-app:${{ github.sha }} 

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1

    - name: Deploy to AKS
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ./kubeconfig
        export KUBECONFIG=./kubeconfig
        kubectl set image deployment/my-node-app-deployment my-node-app=digerate/enhanced-node-app:${{ github.sha }}
